name: build

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'cache tag'
        required: false
        type: string

jobs:
  publish:
    timeout-minutes: 120
    name: ${{ matrix.os }} - Node.js ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # version: [14, 16, 18]
        version: [18]
        os: [ubuntu-latest, windows-2019]

    steps:
      - uses: actions/checkout@v3

      - name: Check submodule hash
        shell: bash
        run: |
          if [ -n "${USE_TAG}" ]; then
            echo "HASH=-${USE_TAG}" >> $GITHUB_OUTPUT
          else
            echo "HASH=$(git submodule status externals/libemoji | awk '{print $1}')" >> $GITHUB_OUTPUT
          fi
        env:
          USE_TAG: ${{ github.event.inputs.tags }}
        id: submodule_hash

      - name: Check cache exists
        uses: actions/cache@v3
        id: submodule_cache
        with:
          path: externals/libemoji/tmp
          key: ${{ runner.os }}-libemoji-${{ steps.submodule_hash.outputs.HASH }}
          lookup-only: true

      - name: Cleanup Diskspace (Ubuntu)
        if: contains(matrix.os, 'ubuntu') && steps.submodule_cache.outputs.cache-hit != 'true'
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          swap-storage: false

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: 'yarn'

      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Install debug tool
        run: go install github.com/chenquan/diskusage@latest

      - name: Install LLVM (Windows)
        if: contains(matrix.os, 'windows')
        uses: KyleMayes/install-llvm-action@v1.7.0
        with:
          version: '3'

      - name: Setup msbuild (Windows)
        if: contains(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1

      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Install libs (Ubuntu)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install git cmake g++ libfontconfig1-dev libx11-dev libxcomposite-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev libfreetype-dev -y

      - name: Install deps
        run: yarn install --frozen-lockfile
        env:
          SKIP_BUILD: true

      - run: yarn setup

      - name: Show disk usage before build
        run: diskusage --dir ${{ github.workspace }}

      - name: Show disk state (Windows)
        if: contains(matrix.os, 'windows')
        shell: powershell
        run: Get-PSDrive

      - run: yarn run build-skia
        if: steps.submodule_cache.outputs.cache-hit != 'true'
        env:
          WORKING_DIR: ${{ github.workspace }}

      - name: Show disk usage
        run: diskusage --dir ${{ github.workspace }}

      - uses: actions/cache/save@v3
        if: steps.submodule_cache.outputs.cache-hit != 'true'
        with:
          path: externals/libemoji/tmp
          key: ${{ runner.os }}-libemoji-${{ steps.submodule_hash.outputs.HASH }}

      - name: Restore cache
        uses: actions/cache/restore@v3
        if: steps.submodule_cache.outputs.cache-hit == 'true'
        with:
          path: externals/libemoji/tmp
          key: ${{ runner.os }}-libemoji-${{ steps.submodule_hash.outputs.HASH }}

      - run: yarn run build-lib
        env:
          WORKING_DIR: ${{ github.workspace }}

      - run: yarn run build
      - run: yarn run pre-build
      - name: Upload prebuilt binaly
        run: yarn run upload ${{ secrets.PREBUILD_TOKEN }}
