name: build

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    timeout-minutes: 60
    name: ${{ matrix.os }} - Node.js ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: [14, 16, 18]
        os: [ubuntu-latest, windows-2019]

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: 'yarn'

      - name: Install libs (Ubuntu)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install git cmake g++ python2 libfontconfig1-dev libx11-dev libxcomposite-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev -y

      - name: Install deps
        run: yarn install --frozen-lockfile
        env:
          SKIP_BUILD: true

      - run: echo "::set-output name=HASH::$(git submodule status externals/libemoji | awk '{print $1}')"
        id: submodule_hash
      - uses: actions/cache@v2
        id: submodule_cache
        with:
          path: |
            externals/libemoji
          key: ${{ runner.os }}-libemoji-${{ steps.submodule_hash.outputs.HASH }}

      - if: steps.submodule_cache.outputs.cache-hit != 'true'
        run: yarn setup
      - if: steps.submodule_cache.outputs.cache-hit == 'true'
        run: yarn setup:native-configure

      - run: yarn build
      - run: yarn prebuild
      - run: yarn upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
