name: build

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    timeout-minutes: 60
    name: ${{ matrix.os }} - Node.js ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # version: [14, 16, 18]
        version: [18]
        os: [ubuntu-latest, windows-2019]
        # os: [windows-2019]

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: 'yarn'

      - name: Install libs (Ubuntu)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install git cmake g++ libfontconfig1-dev libx11-dev libxcomposite-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev -y

      - name: Install libs (Windows)
        if: contains(matrix.os, 'windows')
        uses: KyleMayes/install-llvm-action@v1.7.0
        with:
          version: '3'

      - name: Setup msbuild (Windows)
        if: contains(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install deps
        run: yarn install --frozen-lockfile
        env:
          SKIP_BUILD: true

      - name: Make symbolic link (Windows)
        if: contains(matrix.os, 'windows')
        run: ./scripts/make-symboliclink.bat

      - run: yarn run setup
      - run: yarn run build
      - run: yarn run pre-build
      - run: yarn run upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
