name: build

on:
  workflow_dispatch:

jobs:
  publish:
    timeout-minutes: 120
    name: ${{ matrix.os }} - Node.js ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # version: [14, 16, 18]
        version: [18]
        os: [ubuntu-latest, windows-2019]

    steps:
      - uses: actions/checkout@v3

      - name: Cleanup Diskspace (Ubuntu)
        if: contains(matrix.os, 'ubuntu')
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          swap-storage: false

      - name: Cleanup Diskspace (Windows)
        if: contains(matrix.os, 'windows')
        shell: powershell
        run: |
          Remove-Item -Path "C:\Android" -Recurse -Force
          Remove-Item -Path "C:\Program Files (x86)\Android" -Recurse -Force
          Remove-Item -Path "C:\Program Files (x86)\Epic Games" -Recurse -Force

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: 'yarn'

      - name: Install LLVM (Windows)
        if: contains(matrix.os, 'windows')
        uses: KyleMayes/install-llvm-action@v1.7.0
        with:
          version: '3'

      - name: Setup msbuild (Windows)
        if: contains(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1

      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Install libs (Ubuntu)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install git cmake g++ libfontconfig1-dev libx11-dev libxcomposite-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev libfreetype-dev -y

      - name: Install deps
        run: yarn install --frozen-lockfile
        env:
          SKIP_BUILD: true

      - name: Check submodule hash
        run: |
          echo "\"HASH=" >> libemoji-hash.txt
          git submodule status externals/libemoji | awk '{print $1}' >> libemoji-hash.txt
          echo "\"" >> libemoji-hash.txt
          cat libemoji-hash.txt | sed -z 's/\n//g' >> $GITHUB_OUTPUT
        id: submodule_hash

      - run: yarn setup

      - uses: actions/cache@v3
        id: submodule_cache
        with:
          path: |
            externals/libemoji/tmp
          key: ${{ runner.os }}-libemoji-${{ steps.submodule_hash.outputs.HASH }}

      - run: yarn run build-skia
        if: steps.submodule_cache.outputs.cache-hit != 'true'
        env:
          WORKING_DIR: ${{ github.workspace }}

      - uses: actions/cache/save@v3
        if: steps.submodule_cache.outputs.cache-hit != 'true'
        with:
          path: |
            externals/libemoji/tmp
          key: ${{ runner.os }}-libemoji-${{ steps.submodule_hash.outputs.HASH }}

      - run: yarn run build-lib
        env:
          WORKING_DIR: ${{ github.workspace }}

      - run: yarn run build
      - run: yarn run pre-build
      - name: Upload prebuilt binaly
        run: yarn run upload ${{ secrets.PREBUILD_TOKEN }}
