name: Native CI

on:
  push:
    paths:
      - externals/**
      - src/**
      - __tests__/src/**
  pull_request:
    paths:
      - externals/**
      - src/**
      - __tests__/src/**

jobs:
  lint-and-test:
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: echo "::set-output name=HASH::$(git submodule status externals/libemoji | awk '{print $1}')"
        id: submodule_hash
      - uses: actions/cache@v2
        with:
          path: |
            externals/libemoji/bin
            externals/libemoji/lib
            externals/libemoji/CMakeFiles
          key: ${{ runner.os }}-${{ steps.submodule_hash.outputs.HASH }}

      - name: Install nodejs deps
        run: yarn install --immutable --check-cache

      - run: yarn setup
      - run: yarn lint
      - run: yarn prebuild
      - run: yarn build
      - run: yarn test:cpp
