name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install deps
        run: yarn install --immutable --check-cache
      - run: yarn setup

      - run: echo "::set-output name=HASH::$(git submodule status externals/libemoji | awk '{print $1}')"
        id: submodule_hash
      - uses: actions/cache@v2
        with:
          path: |
            externals/libemoji/bin
            externals/libemoji/lib
            externals/libemoji/CMakeFiles
          key: ${{ runner.os }}-${{ steps.submodule_hash.outputs.HASH }}

      - run: yarn prebuild
      - run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
